# Use Ubuntu 16.04 as base image
FROM ubuntu:16.04

# Install necessary build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    libglu1-mesa-dev \
    libasound2-dev \
    libfreetype6-dev \
    libxpm-dev \
    libxft-dev \
    libxxf86vm-dev \
    libpulse-dev \
    libopenal-dev \
    libwebkit2gtk-4.0-dev \
    libgtk-3-dev \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*
