name: Win32 Weekly

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Build Docker image
          run: |
            docker build --platform linux/amd64 -t blitzmax_win32_cross_compile -f src/scripts/Dockerfile.win32 .
  
        - name: Run build script in Docker
          run: |
            mkdir -p build
            cp src/scripts/build_release.sh build
            docker run -v $GITHUB_WORKSPACE/build:/build -w /build blitzmax_win32_cross_compile ./build_release.sh -l win32 -a x86x64 -b 0.136.3.51 -r x64 -p -t
  
        - name: Populate env variables
          run: |
            echo "VERSION_TAG=$(cat build/version-tag.txt)" >> $GITHUB_ENV
            echo "PACKAGE_NAME=$(cat build/package-name.txt)" >> $GITHUB_ENV
            echo "PACKAGE_MIME_TYPE=$(cat build/package-mime.txt)" >> $GITHUB_ENV

        - name: Set custom tag
          id: custom_tag
          run: |
            echo "tag=v${{ env.VERSION_TAG }}.win32.mingw" >> $GITHUB_OUTPUT

        - name: Create Release and Upload Asset
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.custom_tag.outputs.tag }}
            name: "[weekly] BlitzMax Win32 (mingw) v${{ env.VERSION_TAG }}"
            body: |
                BlitzMax, Windows edition, with both x86 and x64 MinGW-w64 distributions.

                Includes SDL backend, mojo2, Crypto, Audio, Archive, Image, Math, Net, Random, Text and Steam.
                
                ### Installation notes
                
                See the [Getting Started Guide](https://blitzmax.org/docs/en/setup/win32/) at the BlitzMax website.

                *Note: This is a weekly build, and may contain bugs. Use at your own risk.*
            prerelease: true
            files: ./build/${{ env.PACKAGE_NAME }}
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
